### ISSUE TITLE
Self Signed Cert issue

### ISSUE THREAD

**Issue by magicalyak** [f5devcentral/vscode-nginx#2]
Hitting an error on the plugin where a self-signed cert is giving an error (won't populate the instances).  Using postman on the box works, UI and swagger-ui works and the CURL works.  The only thing left is the certificate or using an IP.  Can we add a variable to disable SSL strict checking?

**Comment by magicalyak** [comment]
![image](https://user-images.githubusercontent.com/6165889/137985543-eb7688fc-388e-4508-89dc-3100668a700b.png)

**Comment by DumpySquare** [comment]
Yes.  I had someone ask for the opposite on the main vscode-f5 extension.  Developing the feature here might be a bit easier.

**Comment by magicalyak** [comment]
It appears the certs are all or nothing so we may need to close and not do this.  If you can't do trust not sure it's worth enabling Pandora's box on this.

**Comment by DumpySquare** [comment]
@magicalyak, so where do we want to go with this?  close for now?
