### ISSUE TITLE
Enable "Reset" button to update the config to the latest on disk

### ISSUE THREAD

**Issue by magicalyak** [f5devcentral/vscode-nginx#3]
Add a Reset button to pull the latest config from the instance like in the UI.
![image](https://user-images.githubusercontent.com/6165889/138965317-c938e9bb-38db-4d44-8de7-e659eb9d3398.png)

Needs a current=true on the GET config API call
curl -X GET "https://24f6fbc0-1648-4ad4-9fda-a12982a1bfa7.access.udf.f5.com/api/v0/instances/144b1447-d45c-4452-82ea-be4cfe9e0e7a/config?current=true" -H  "accept: application/json"

**Comment by DumpySquare** [comment]
this was added in v0.6.0 just released
